### ISSUE TITLE
MOLD website and SPARQL endpoint not working?

### ISSUE THREAD

**Issue by maulikkamdar** [mo-ld/mold-webapp#3]
Hi,
I am not sure if this is the right issue queue to put this, but it seems the MOLD website and the SPARQL endpoint (http://vt.mo-ld.org/sparql) are not available currently. 
Have the services been discontinued?
Thanks

**Comment by zorino** [comment]
Hi Maulik,
I've transferred the domain to @micheldumontier at another registrar.
It should be setup soon.

**Comment by maulikkamdar** [comment]
Thanks for answering! Is there any accessible RDF dump that I can deploy on a local virtuoso for my experiments, till the endpoint is set up?

**Comment by zorino** [comment]
OK, I've made the virtuoso dumps and tsv triples available here -
http://perso.genome.ulaval.ca/~deraspem/mo-ld/

**Comment by micheldumontier** [comment]
I pointed the main domain, and the subdomains api, vt, ldf to the server.  Web site went up first, but i'm still waiting for dns to catchup on subdomains.  @zorino is there any other configuration required?

**Comment by zorino** [comment]
Thank you @micheldumontier 
That should be all for the configuration, everything is responding on my side main site and subdomains.

**Comment by maulikkamdar** [comment]
Thanks!
